name: CI

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  test:
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - 25.1
          - 25.2
          - 25.3
          - 26.1
          - 26.2
          - 26.3
          - 27.1

        include:
          - emacs_version: 25.1
            dmg: Emacs-25.1-1-universal.dmg
          - emacs_version: 25.2
            dmg: Emacs-25.2-universal.dmg
          - emacs_version: 25.3
            dmg: Emacs-25.3-universal.dmg
          - emacs_version: 26.1
            dmg: Emacs-26.1-2-universal.dmg
          - emacs_version: 26.2
            dmg: Emacs-26.2-universal.dmg
          - emacs_version: 26.3
            dmg: Emacs-26.3-universal.dmg
          - emacs_version: 27.1
            dmg: Emacs-27.1-1-universal.dmg

    env:
      EMACS: /Applications/Emacs.app/Contents/MacOS/Emacs

    steps:
    - name: Set up Emacs
      run: |
        curl -o ${{matrix.dmg}} https://emacsformacosx.com/download/emacs-builds/${{matrix.dmg}}
        hdiutil attach -mountpoint /Volumes/${{matrix.dmg}} ${{matrix.dmg}} -nobrowse
        cp -R /Volumes/${{matrix.dmg}}/Emacs.app /Applications/

    - name: Set up Cask
      uses: conao3/setup-cask@master
      with:
        version: snapshot

    - name: Check out the source code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: cask install --debug

    - name: Run tests
      run: |
        cask build
        cask exec ert-runner --reporter ert+duration
